init_features: 16
in_days: 4
out_days: 10
epochs: 2
learning_rate: 0.001
batch_size: 1
split: 0.2
use_16bit: true
gpus: 1
optim: one_cycle
dry_run: false
find_lr: false
search_bs: false
case_study: false
clip_output: false
boxcox: 0.1182
binned: [0, 5.2, 11.2, 21.3, 38.0, 50]
round_to_zero: false
isolate_frp: false
date_range: false
cb_loss: false
chronological_split: false
undersample: false
model: unet_tapered
out: fwi_reanalysis
benchmark: false
forecast_dir: null
forcings_dir: data/actual/deepfwi-forcings
reanalysis_dir: data/actual/deepfwi-reanalysis/fwi-reanalysis
frp_dir: null
mask: src/dataloader/mask/reanalysis_mask.npy
comment: false
checkpoint_file: false
